document:
  name: Esperienza dei cittadini con il once only
  description: |
    Questa documentazione è in fase di pubblicazione e sarà disponibile a breve.
    Le raccomandazioni di UX per la progettazione di servizi abilitati dall'interoperabilità saranno presto consultabili su questa pagina.    
  tags:
    - interoperabilità
    - once only
    - UX
    - esperienza dei cittadini
    - PDND
    