document:
  name: "Raccomandazioni UX per il once only" 
  description: "Questa documentazione raccoglie raccomandazioni per guidare gli enti nella progettazione dei servizi abilitati dall’interoperabilità."      
  tags:
    - interoperabilità
    - once only
    - UX
    - esperienza dei cittadini
    - PDND
